name: Build and Test

on: 
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    name: Build
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
  
    - name: 'Build'
      run: dotnet build './AzureAppRegistrationsManager/AzureAppRegistrationsManager.csproj' -c Release